import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// are you there? Hello, do you have abackgourndimage?
// can you hear me?
// no
// please check your seeeing, I am sure I 
export default function Home() {
  return (
    <>
      <div>
        <Head>
          <div className={`text-center ${styles.header}`}>Kostener Versand in Deutschland</div>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.header}></div>
            <h1 className={`text-6xl text-black text-center ${styles.header}`}>Sehen Sie sich unsere <br/>Auswahl an</h1>
        </div>
        <div className={styles.headerContainer}>
          
  
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <span className={styles.logo}>
              <Image src="/nuzer_favicon.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
      </div>
    </>
  )
}
